hydra:
  run:
    dir: .
  output_subdir: null

cluster:
  num_nodes: 2
  component_placement:
    actor:
      node_group: sim
      placement: 0
    rollout:
      node_group: sim
      placement: 0
    env:
      node_group: real
      placement: 0
  node_groups:
    - label: real
      node_ranks: 0
      hardware:
        type: Franka
        configs:
          - robot_ip: 192.168.1.2
            node_rank: 0
    - label: sim
      node_ranks: 1

runner:
  only_eval: true
  save_interval: -1
  resume_dir: null
  ckpt_path: /home/ubuntu/shiliangzhi/co-training/RLinf/results/co_rl_peg_insertion_bc10000_cnn_wrist_state/20260911-135855/co_rl_peg_insertion_bc10000_cnn_wrist_state/checkpoints/global_step_80/actor/model_state_dict/full_weights.pt
  logger:
    log_path: ${oc.env:RLINF_LOG_PATH}/real_eval_peg_insertion_cnn_wrist_state/${oc.env:RLINF_EVAL_RUN_ID}
    experiment_name: real_eval_peg_insertion_cnn_wrist_state

algorithm:
  sim_real_rl_co_training: false

env:
  train:
    co_training_env_cfg:
      auto_reset: false
      ignore_terminations: false
      total_num_envs: 1
      video_cfg:
        save_video: true
        record_rollout_interval: 1
        video_base_dir: runtime_env:RLINF_LOG_PATH/${evaluation.run_relative_dir}/video/real
  eval: ${env.train.co_training_env_cfg}

actor:
  initial_checkpoint_exclude_keys: []

rollout:
  enable_torch_compile: false
  enable_cuda_graph: false

evaluation:
  training_config: co_rl_peg_insertion_bc10000_cnn_wrist_state
  num_episodes: 40
  policy_mode: deterministic
  check_only: false
  run_relative_dir: ${runner.logger.experiment_name}/${oc.env:RLINF_EVAL_RUN_ID}
