env_type: realworld
total_num_envs: null
auto_reset: true
ignore_terminations: false
seed: 0
group_size: 1
use_fixed_reset_state_ids: false
max_steps_per_rollout_epoch: 120
max_episode_steps: 120
use_spacemouse: false
use_gello: false
no_gripper: false
use_relative_frame: true
keyboard_reward_wrapper: pnp_human
main_image_key: wrist_2
include_states_in_obs: false

human_feedback_cfg:
  success_key: s
  failure_key: f
  abort_key: x
  ready_key: r
  wait_for_reset_ready: true
  reset_poll_interval: 0.05
  reset_ready_timeout: null

video_cfg:
  save_video: false
  info_on_video: true
  include_extra_views: true
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  id: FrankaPickAndPlaceEnv-v1

override_cfg:
  camera_serials:
    - ${oc.env:RLINF_REAL_WRIST_CAMERA}
    - ${oc.env:RLINF_REAL_POLICY_CAMERA}
  is_dummy: false
  enable_camera_player: true
  use_target_controller: true
  target_ee_pose: [0.55865414, 0.16184118, 0.02504874, 3.00194796, 0.0286977, -0.05498182]
  reset_ee_pose: [0.55865414, 0.16184118, 0.22504874, 3.00194796, 0.0286977, -0.05498182]
  action_scale: [0.01, 0.05, 1.0]
  clip_x_range: 0.3
  clip_y_range: 0.3
  clip_z_range_high: 0.2
  clip_z_range_low: 0.06004874
  clip_rz_range: 0.5
  clip_rp_range: 0.01
  random_xy_range: 0.015
  random_rz_range: 0.34906585
  enable_random_reset: true
  enable_inner_safety_box: false
  joint_reset_qpos: [0.0, 0.39269908, 0.0, -1.96349541, 0.0, 2.35619449, 0.78539816]
  step_frequency: 10.0
  max_num_steps: 120
  use_dense_reward: false
  use_reward_model: false
  enable_gripper_penalty: false
  use_zero_one_gripper_action: false
  binary_gripper_threshold: 0.5
  gripper_min_command_interval: 1.0
  gripper_config:
    open_width: 0.08
    open_speed: 0.04
    close_width: 0.045
    close_speed: 0.03
    close_force: 15.0
    epsilon_inner: 0.005
    epsilon_outer: 0.01
  enable_downward_contact_failure: false
