env_type: realworld
total_num_envs: null
auto_reset: true
ignore_terminations: false
seed: 0
group_size: 1
use_fixed_reset_state_ids: false
max_steps_per_rollout_epoch: 120
max_episode_steps: 120
use_spacemouse: false
use_gello: false
no_gripper: false
use_relative_frame: false
keyboard_reward_wrapper: pnp_human
main_image_key: wrist_2
include_states_in_obs: false

human_feedback_cfg:
  success_key: s
  failure_key: f
  abort_key: x
  ready_key: r
  wait_for_reset_ready: true
  reset_poll_interval: 0.05
  reset_ready_timeout: null

video_cfg:
  save_video: false
  info_on_video: true
  include_extra_views: true
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  id: FrankaPickAndPlaceEnv-v1
